feat(api): URM rules endpoints
GrizzHacks/hackathon-portal pull request #105
Opened 2021-03-31 01:30 UTC by shriyash

2021-04-14 02:35 UTC, shriyash commented
Tests via API Explorer (ORGANIZER user):

### POST urm/rules/
```
{
    "ruleId": "rule1",
    "ruleOrder": 1,
    "ruleName": "RuleName1",
    "applicationQuestionId": "applicationQuestion1"
}
```
> Status 201

### POST urm/rules
```
{
  "ruleId": "rule2",
  "ruleOrder": 2,
  "ruleName": "RuleName2",
  "applicationQuestionId": "applicationQuestion2",
  "acceptedValues": "^[a-z|A-Z|0-9|_]*$",
  "matchesRemaining": 2
}
```
> Status 201

### PATCH urm/rules/rule1
```
{
    "applicationQuestionId": "applicationQuestion1",
    "acceptedValues": "^[a-z|A-Z|0-9|_]*$",
    "matchesRemaining": 1
}
```
> Status 200

### GET urm/rules/rule1
Result:
```
{"ruleOrder":1,"ruleName":"RuleName1","ruleId":"rule1","applicationQuestionId":"applicationQuestion1","matchesRemaining":1,"acceptedValues":"^[a-z|A-Z|0-9|_]*$"}
```
> Status 200

### GET urm/rules
```
{"rules":[{"ruleOrder":1,"ruleName":"RuleName1","ruleId":"rule1","applicationQuestionId":"applicationQuestion1","matchesRemaining":1,"acceptedValues":"^[a-z|A-Z|0-9|_]*$"},{"matchesRemaining":2,"ruleOrder":2,"ruleName":"RuleName2","ruleId":"rule2","applicationQuestionId":"applicationQuestion2","acceptedValues":"^[a-z|A-Z|0-9|_]*$"}]}
```
> Status 200

### DELETE urm/rules/rule2

> Status 200

2021-04-15 01:28 UTC, andrewdimmer requested changes
One minor change, then you should be good to go!

2021-04-15 01:28 UTC, andrewdimmer commented on functions/src/modules/urm/rules/createRules.ts
> +  const body = res.locals.parsedBody as URMRulesCreateRequest;
Can we initialize `acceptedValues` to an empty array if none is provided, and `matchesRemaining` to 1 if none is provided?

2021-04-15 01:41 UTC, andrewdimmer approved these changes
Looks good to me!

2021-04-15 02:26 UTC, merged