feat(api): Create all PM/Category endpoints and datatype
GrizzHacks/hackathon-portal pull request #77
Opened 2021-03-13 05:58 UTC by nicksinishtaj

Closing #33

2021-03-13 09:29 UTC, andrewdimmer requested changes
Generally a great start! There are a few minor fixes, but most of the comments are regarding broader design choices that I just don't think we've worked out entirely. Some things to discuss as a group include:

- Should the "approval process" have it's own endpoint separate from the regular update, so it works more inline with a button press, or is that something that the UI should handle?
- At what point in the process should the `approvalStatus` matter? Should it be checked for all roles, or do we just check for certain cases (like public get or sponsor edit)?
- What fields for a prize category should be required, and what should be optional?
- What rights does a SPONSOR user have? Can they create and delete their own category, or should an organizer do those steps and a sponsor only edits?
- What information should be publicly exposed via the API for the purpose of creating a Live Site from the API?

In addition to these changes, I think that it'd be good if there could be a little more testing from the API explorer, similar to what was done for #7 and #8 .

2021-03-13 09:29 UTC, andrewdimmer commented on @types/modules/stpm/categories.d.ts
> +    approvalStatus: "approved" | "rejected" | "inProgress" | "awaitingApproval" | "public";
Thoughts on making this optional and defaulting it to `inProgress`?

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +      prizeCategoryDescription: { rules: ["string"]},
Should this be required? If so, we should tag it as required. If not, then we should mark it optional in the data type.

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +      eligibility: { rules: ["string"]},
I think that these would all benefit from the `emptystring` type added in #75 , might be worth merging that first... Likewise, `approvalStatus` might want to go to a Enum if it is even possible to set during the creation. Food for though, and something we'll likely want to discuss.

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +      companyId: { rules: ["string"], required: true },
This probably shouldn't be required; as not all prizes are sponsored...

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +    organizer: { accepted: validate },
What are our thoughts on the process flow for a SPONSOR user? Does an organizer need to create the category with dummy information, or can a sponsor start the create process? I don't know if we have an answer to this yet, but something I think is worth discussing.

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/deleteCategory.ts
> +    organizer: { accepted: execute },
As with create, should sponsors be able to delete a prize category?

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/deleteCategory.ts
> +    .doc(req.params.companyId)
I think this should be `categoryId`, right?
```suggestion
    .doc(req.params.categoryId)
```

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +    sponsor: { accepted: executeIfCategoryMatches },
I think that this needs to be public for everyone, as it will need to be exposed for the live site, right?

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +    .doc(req.params.prizeCategoryId)
Once again, we should check what the final parameter is, but I think it is just `categoryId`.
```suggestion
    .doc(req.params.categoryId)
```

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +};
Do we need to restrict this? Is this required, or should we make the GET public to all?

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/listCategories.ts
> +    organizer: { accepted: execute },
Likewise, this should likely be public...

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +    sponsor: { accepted: executeIfSponsorMatches },
This is good that it is restricted to just organizers and the sponsor company that has the prize. :)

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +        companyId: { rules: ["string"], required: true },
If this is update, there shouldn't be any required fields. Also, some of the types from #75 might be worth pulling in.

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +          eligibility: { rules: ["string"]},
Same as above, but I don't think there should be any required fields for update.

2021-03-13 09:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +    .doc(req.params.prizeCategoryId)
Once again, we need to check what the parameter id is; I think it is just `categoryId`.
```suggestion
    .doc(req.params.categoryId)
```

2021-03-13 16:25 UTC, nicksinishtaj commented on .gitignore
> +/.vs
Yeah we could block it, was using the git UI in Visual Studio 2019 so that's where they're from

2021-03-13 17:48 UTC, nicksinishtaj commented on functions/src/modules/pm/categories/createCategory.ts
> +      prizeCategoryDescription: { rules: ["string"]},
Should def be required

2021-03-13 17:49 UTC, nicksinishtaj commented on functions/src/modules/pm/categories/getCategory.ts
> +    sponsor: { accepted: executeIfCategoryMatches },
Good catch

2021-03-13 17:52 UTC, nicksinishtaj commented on functions/src/modules/pm/categories/createCategory.ts
> +    organizer: { accepted: validate },
I'd assume the category should be first created by an organizer with dummy info, since we'll have our base categories and any modifications should be handled by us directly. Open to suggestions though.

2021-03-13 17:56 UTC, nicksinishtaj commented on functions/src/modules/pm/categories/createCategory.ts
> +      eligibility: { rules: ["string"]},
Are we able to use an Enum in the validation rules?

2021-03-13 18:01 UTC, nicksinishtaj commented on functions/src/modules/pm/categories/deleteCategory.ts
> +    organizer: { accepted: execute },
I say no but that can be discussed with team

2021-03-14 02:50 UTC, nicksinishtaj commented
### Tests via API Explorer (ORGANIZER user):
**POST pm/categories/**

```JSON
{
    "categoryId": "category1",
    "prizeCategoryName": "Best Web App",
    "prizeCategoryDescription": "Best web app ever"
}

Response
Status
201

Response
Status
Pending response...


```

> Status: 201

**GET pm/categories/category1**

pm/categories/category1

> Status: 200
> Body: {"approvalStatus":"inProgress","prizeCategoryName":"Best Web App","prizeCategoryDescription":"Best web app ever","categoryId":"category1"}

**PATCH pm/categories/category1**

```JSON
{
	"prizeCategoryName": "El Web Applicacion Mejor"
}
```

> Status: 200

**GET pm/categories/category1**

> Status: 200
> Body: {"approvalStatus":"inProgress","prizeCategoryDescription":"Best web app ever","categoryId":"category1","prizeCategoryName":"El Web Applicacion Mejor"}

**POST pm/categories/**

```JSON
{
    "categoryId": "category2",
    "prizeCategoryName": "Best Rookie Hack",
    "prizeCategoryDescription": "Best project for a first-time hackathon attendee"
}
```

> Status: 201

**GET pm/categories/**

> Status: 200
> Body: {"prizeCategories":[{"approvalStatus":"inProgress","prizeCategoryName":"Best Rookie Hack","prizeCategoryDescription":"Best project for a first-time hackathon attendee","categoryId":"category2"},{"approvalStatus":"inProgress","prizeCategoryDescription":"Best web app ever","categoryId":"category1","prizeCategoryName":"El Web Applicacion Mejor"}]}


**DELETE pm/categories/category1**

> Status: 200

**GET pm/categories/**

> Status: 200
> Body: {"prizeCategories":[{"approvalStatus":"inProgress","prizeCategoryName":"Best Rookie Hack","prizeCategoryDescription":"Best project for a first-time hackathon attendee","categoryId":"category2"}]}

2021-03-14 04:30 UTC, andrewdimmer requested changes
Couple of updates required based mostly on when information is available, but should be pretty fast to fix for the most part.

2021-03-14 04:30 UTC, andrewdimmer commented on @types/modules/pm/categories.d.ts
> +    approvalStatus?: "approved" | "rejected" | "inProgress" | "awaitingApproval" | "public";
If we keep this with "public", we'll have a 2-stage approval process; if we want to streamline it, it might be worth it to just display publicly any "approved" prizes.
```suggestion
    approvalStatus?: "approved" | "rejected" | "inProgress" | "awaitingApproval";
```

2021-03-14 04:30 UTC, andrewdimmer commented on @types/modules/pm/categories.d.ts
> +    approvalStatus: "approved" | "rejected" | "inProgress" | "awaitingApproval" | "public";
If we keep this with "public", we'll have a 2-stage approval process; if we want to streamline it, it might be worth it to just display publicly any "approved" prizes.
```suggestion
    approvalStatus: "approved" | "rejected" | "inProgress" | "awaitingApproval";
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +        rules: ["string"],
The `rules` for an enum are the allowed values; if we keep this as string, the only accepted value would be "string" itself. Therefore, this should be the values itself that we want to allow; likely "approved", "rejected", "inProgress", or "awaitingApproval" for organizers, and just "inProgress" or "awaitingApproval" for sponsors.
```suggestion
        rules: (res.locals.permissions as UserPermission).role === "ORGANIZER ? ["approved", "rejected", "inProgress", "awaitingApproval"] : ["inProgress", "awaitingApproval"],
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +      companyId: { rules: ["string", "emptystring"]},
Thoughts on either auto-filling the company if a sponsor creates a prize category, or making company required for sponsor users? If so, it might be worth having a separate validation function for SPONSOR users, or adding some conditional logic here to check that if a sponsor creates it, it contains their companyId.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +
If we don't want to muddy the validator with the sponsor logic, here would be another good place to either auto-fill the companyId if the user is a SPONSOR user, or error out if they provide a companyId other than their own.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +
Actually, the more that I think about, I think it would be easier to keep the validator the same, and just add the logic here...

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/createCategory.ts
> +    .doc(body.categoryId)
I think that this is still "prizeCategoryId", right?
```suggestion
    .doc(body.prizeCategoryId)
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/deleteCategory.ts
> +    sponsor: {accepted: executeIfSponsorMatches }
No action required here, just confirming that we're allowing a sponsor to delete a prize category, right? If not, we should remove this line.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/deleteCategory.ts
> +      `A sponsor from ${sponsorCompany} tried viewing information for ${req.params.companyId}.`,
Might be worth making this error message more descriptive, something like below:
```suggestion
      `A sponsor from ${sponsorCompany} tried deleting prizeCategory ${req.params.categoryId}.`,
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +  if (sponsorCompany === req.params.companyId || req.params.approvalStatus === "approved") {
We're going to need to read the current data in the database to get the approvalStatus. Might be worth restructuring these calls to have execute as the public one, but it takes in an optional boolean parameter that allows it to get non-approved events. If you want to talk about this over a video call, that might be easier.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +  if (req.params.approvalStatus === "approved") {
Likewise, might be worth restructuring...

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/getCategory.ts
> +    public: executeIfApprovalStatusApproved
I think we need to allow "public" access to all roles even if they are "pending" or "rejected", right?

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/listCategories.ts
> +    public: executeIfApprovalStatusApproved
Same comments as with GET, I think we'll need to grant access to all roles regardless of acceptance, and it might be worth a restructure based on when we do the database read.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +          rules: ["string"],
Same as with create, this needs to contain the actual values.
```suggestion
          rules: ["approved", "rejected", "inProgress", "awaitingApproval"],
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +          approvalStatus: { rules: ["string"]},
This should also switch to an Enum.

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +  }
Because this is an update, undefined just means "no change" and we don't want to override it.
```suggestion
```

2021-03-14 04:30 UTC, andrewdimmer commented on functions/src/modules/pm/categories/updateCategory.ts
> +        `A sponsor from ${sponsorCompany} tried viewing information for ${req.params.companyId}.`,
Let's make this a little more descriptive as well.
```suggestion
        `A sponsor from ${sponsorCompany} tried updating prizeCategory ${req.params.categoryId}.`,
```

2021-03-14 07:14 UTC, andrewdimmer approved these changes
Looks good to me! We'll want to do more testing for other types of users once we can automate integration testing, but in the mean time let's get this merged!

2021-03-14 07:16 UTC, merged