feat(api): Create all METM/mini-event endpoints and datatype
GrizzHacks/hackathon-portal pull request #78
Opened 2021-03-13 07:16 UTC by nicksinishtaj

Closes #67

2021-03-13 09:48 UTC, andrewdimmer requested changes
Great start! A few naming convention changes, but you should be able to accept all of them in bulk from GitHub directly.

One thing that I think we do need to discuss as a team though is the relationship between an Event and a Time Slot in the MEWM. Can they exist independently, or does an Event need to be in a Time Slot? 

In addition to these changes, I think that it'd be good if there could be a little more testing from the API explorer, similar to what was done for #7 and #8 .

2021-03-13 09:48 UTC, andrewdimmer commented on @types/modules/stpm/minievents.d.ts
> +declare interface METMMiniEventUpdateRequest {
Heads up! It's the "Mini Events and Workshops Module" (ME**W**M). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
declare interface MEWMEventUpdateRequest {

```

2021-03-13 09:48 UTC, andrewdimmer commented on @types/modules/stpm/minievents.d.ts
> +declare interface METMMiniEventCreateRequest extends METMMiniEventUpdateRequest{
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
declare interface MEWMEventCreateRequest extends MEWMEventUpdateRequest {
```

2021-03-13 09:48 UTC, andrewdimmer commented on @types/modules/stpm/minievents.d.ts
> +declare interface METMMiniEvent extends METMMiniEventCreateRequest{
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
declare interface MEWMEvent extends MEWMEventCreateRequest{
```

2021-03-13 09:48 UTC, andrewdimmer commented on @types/modules/stpm/minievents.d.ts
> +    speakers?: string[];
I don't think any of these should be optional at this point, right?
```suggestion
    location: string;
    joinLink: string;
    joinLinkToPresenters: number;
    joinLinkToAttendees: number;
    companyId: string;
    managers: string[];
    speakers: string[];
```

2021-03-13 09:48 UTC, andrewdimmer commented on @types/modules/stpm/minievents.d.ts
> +    miniEvents: METMMiniEvent[];
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
declare interface MEWMEventList {
    events: MEWMEvent[];
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/createEvent.ts
> +      joinLinkToAttendees: { rules: ["string"]},
This is a number in the database, right?
```suggestion
      joinLinkToPresenters: { rules: ["number"]},
      joinLinkToAttendees: { rules: ["number"]},
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/createEvent.ts
> +    .collection("miniEvents")
I believe that this is just "events".
```suggestion
    .collection("events")
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/createEvent.ts
> +  const body = res.locals.parsedBody as METMMiniEventCreateRequest;
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
  const body = res.locals.parsedBody as MEWMEventCreateRequest;
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/deleteEvent.ts
> +    .collection("miniEvents")
I believe that this is just "events".
```suggestion
    .collection("events")
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/getEvent.ts
> +    hacker: { accepted: execute },
I think that this should be open to everyone, regardless if they are accepted? Thoughts for how this should relate to the registration system?

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/getEvent.ts
> +    .collection("miniEvents")
I believe that this is just "events".
```suggestion
    .collection("events")
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/getEvent.ts
> +      const data = document.data() as METMMiniEvent | undefined;
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
      const data = document.data() as MEWMEvent | undefined;
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/getEvent.ts
> +        errorHandler(`miniEvents/${req.params.eventId} have no data.`);
```suggestion
        errorHandler(`events/${req.params.eventId} have no data.`);
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/listEvents.ts
> +    hacker: { accepted: execute },
As with the single get, I think that this should be open to everyone, regardless if they are accepted? Thoughts for how this should relate to the registration system?

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/createEvent.ts
> +const execute: ExpressFunction = (req, res, next) => {
How does this interact with `timeslots`? Can you have an event without a time slot? Should we add validation, and if so at what point? How do these connect? This might not be as cut and dry as some of the other endpoints...

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/listEvents.ts
> +      const miniEvents: METMMiniEvent[] = [];
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
      const events: MEWMEvent[] = [];
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/listEvents.ts
> +        miniEvents.push(doc.data() as METMMiniEvent);
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
        events.push(doc.data() as MEWMEvent);
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/listEvents.ts
> +        .send(JSON.stringify({ miniEvents } as METMMiniEventList));
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
        .send(JSON.stringify({ events } as MEWMEventList));
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/listEvents.ts
> +    .collection("miniEvents")
I believe that this is just "events".
```suggestion
    .collection("events")
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/updateEvent.ts
> +        virtual: { rules: ["boolean"], required: true },
For update, I think all fields are optional, right?

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/updateEvent.ts
> +        virtual: { rules: ["boolean"], required: true },
For update, I think all fields are optional, right?

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/updateEvent.ts
> +    .collection("miniEvents")
I believe that this is just "events".
```suggestion
    .collection("events")
```

2021-03-13 09:48 UTC, andrewdimmer commented on functions/src/modules/mewm/events/updateEvent.ts
> +    .update(res.locals.parsedBody as METMMiniEventUpdateRequest)
Heads up! It's the "Mini Events and Workshops Module" (MEWM). Also, I think that these are just referred to as "Events" and not "Mini Events" as they can also include things like deadlines or meals.
```suggestion
    .update(res.locals.parsedBody as MEWMEventUpdateRequest)
```

2021-03-13 19:17 UTC, nicksinishtaj commented on functions/src/modules/mewm/events/createEvent.ts
> +const execute: ExpressFunction = (req, res, next) => {
Per documentation it's a separate collection altogether

2021-03-13 23:43 UTC, shriyash commented on @types/modules/stpm/minievents.d.ts
> +declare interface MEWMEventUpdateRequest {
should this file go in a @types/modules/mewm folder?

2021-03-14 02:07 UTC, nicksinishtaj commented
### Tests via API Explorer (ORGANIZER user):
**POST mewm/events/**

```JSON
{
    "eventId": "event1",
    "eventName": "Ejub's Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": true
}

Response
Status
Pending response...


```

> Status: 201

**GET mewm/events/event1**

mewm/events/event1

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's Excel Contest"}

**PATCH mewm/events/event1**

```JSON
{
	"eventName": "ejub excel"
}
```

> Status: 200

**GET mewm/events/event1**

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}

**POST mewm/events/**

```JSON
{
    "eventId": "event2",
    "eventName": "Ejub's LIVE Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": false
}
```

> Status: 201

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"},{"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}]}



**DELETE mewm/events/event1**

> Status: 200

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"}]}

2021-03-14 08:00 UTC, andrewdimmer approved these changes
@nicksinishtaj If these last changes look good, then you should be all set to merge!

2021-03-14 17:07 UTC, andrewdimmer requested changes

2021-03-14 17:07 UTC, andrewdimmer commented on functions/src/modules/mewm/events/deleteEvent.ts
> +          `A sponsor from ${sponsorCompany} tried deleting the approved event ${req.params.eventId}.`,
At this point the event is not approved; it just matches another company id...

2021-03-14 17:19 UTC, andrewdimmer approved these changes
Looks good to me!

2021-03-14 17:30 UTC, merged