MEWM timeslots endpoints
GrizzHacks/hackathon-portal pull request #81
Opened 2021-03-13 19:28 UTC by trode21

2021-03-17 23:03 UTC, nicksinishtaj commented
Can you quickly do the following:

Copy paste this comment I have right below here, and then update with your endpoints and the data you're using to verify in the API explorer. Just makes it easier when referencing back to these what test data to run.

### Tests via API Explorer (ORGANIZER user):
**POST mewm/events/**

```JSON
{
    "eventId": "event1",
    "eventName": "Ejub's Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": true
}
```

> Status: 201

**GET mewm/events/event1**

mewm/events/event1

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's Excel Contest"}

**PATCH mewm/events/event1**

```JSON
{
	"eventName": "ejub excel"
}
```

> Status: 200

**GET mewm/events/event1**

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}

**POST mewm/events/**

```JSON
{
    "eventId": "event2",
    "eventName": "Ejub's LIVE Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": false
}
```

> Status: 201

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"},{"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}]}



**DELETE mewm/events/event1**

> Status: 200

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"}]}

2021-03-31 03:42 UTC, trode21 commented
Tests via API Explorer (ORGANIZER user):
POST mewm/timeslots

{
"timeslotId": "1",
"startTime": "1:00pm",
"endTime": "2:00pm",
"eventTypeId": "2",
"eventId" : "true"

}

Status: 201

GET mewm/timeslots/1

mewm/timeslots/1

Status: 200
Body: {"eventId":"true","eventTypeId":"2","timeslotId":"1","startTime":"1:00pm","endTime":"2:00pm"}

PATCH mewm/timeslots/event1

{

"startTime": "1:30pm"

}
Status: 200

GET mewm/timeslots/1

Status: 200
Body: {"eventId":"true","eventTypeId":"2","timeslotId":"1","endTime":"2:00pm","startTime":"1:30pm"}

POST mewm/timeslots/

{
"timeslotId": "2",
"startTime": "2:00pm",
"endTime": "3:00pm",
"eventTypeId": "2",
"eventId" : "true"

}
Status: 201

GET mewm/timeslots/

Status: 200
Body:  {"timeslots":[{"eventId":"true","eventTypeId":"2","timeslotId":"1","startTime":"1:00pm","endTime":"2:00pm"},{"eventId":"true","eventTypeId":"2","timeslotId":"2","startTime":"2:00pm","endTime":"3:00pm"}]}

DELETE mewm/timeslots/1

Status: 200

GET mewm/timeslots/

Status: 200
Body: {"timeslots":[{"eventId":"true","eventTypeId":"2","timeslotId":"2","startTime":"2:00pm","endTime":"3:00pm"}]}

2021-04-01 01:15 UTC, andrewdimmer requested changes
Few minor tweaks that you should be able to accept as a batch from https://github.com/GrizzHacks/hackathon-portal/pull/81/files, then you should be good to merge!

2021-04-01 01:15 UTC, andrewdimmer commented on @types/modules/mewm/timeslots.d.ts
> +
We can remove this extra line.
```suggestion
```

2021-04-01 01:15 UTC, andrewdimmer commented on @types/modules/mewm/timeslots.d.ts
> +    endTime: string;
I think we inherit both of these from the create request, so let's just leave this interface blank as a place holder.
```suggestion
```

2021-04-01 01:15 UTC, andrewdimmer commented on functions/src/modules/mewm/timeslots/updateTimeslot.ts
> +      timeslotId: { rules: ["string"] },
Once an id is given, it can't be updated.
```suggestion
```

2021-04-01 01:15 UTC, andrewdimmer commented on functions/src/modules/mewm/timeslots/listTimeslots.ts
> +
This is identical to the `execute` function, so we should be able to just clean this up.
```suggestion
```

2021-04-01 01:15 UTC, andrewdimmer commented on functions/src/modules/mewm/timeslots/listTimeslots.ts
> +      rejected: executeIfApproved,
Let's just keep this to approved organizers for now.
```suggestion
```

2021-04-01 01:36 UTC, andrewdimmer approved these changes
Once the build checks finish, this should be good to merge!

2021-04-01 01:45 UTC, merged