feat(api): Create all mewm/event type endpoints
GrizzHacks/hackathon-portal pull request #82
Opened 2021-03-13 19:34 UTC by shriyash

2021-03-17 23:02 UTC, nicksinishtaj commented
Can you quickly do the following:

Copy paste this comment I have right below here, and then update with your endpoints and the data you're using to verify in the API explorer. Just makes it easier when referencing back to these what test data to run.

Example is from my PR and what I used to test the endpoints

### Tests via API Explorer (ORGANIZER user):
**POST mewm/events/**

```JSON
{
    "eventId": "event1",
    "eventName": "Ejub's Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": true
}
```

> Status: 201

**GET mewm/events/event1**

mewm/events/event1

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's Excel Contest"}

**PATCH mewm/events/event1**

```JSON
{
	"eventName": "ejub excel"
}
```

> Status: 200

**GET mewm/events/event1**

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}

**POST mewm/events/**

```JSON
{
    "eventId": "event2",
    "eventName": "Ejub's LIVE Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": false
}
```

> Status: 201

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"},{"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}]}



**DELETE mewm/events/event1**

> Status: 200

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"}]}

2021-03-18 01:40 UTC, shriyash commented
Tests via API Explorer (ORGANIZER user):
### POST mewm/types/
```
{
    "eventTypeId": "eventType1",
    "eventTypeName": "Workshop",
    "eventTypeDescription": "A technical talk where a speaker will guide attendees through an introduction or exploration of a topic"
},
{
    "eventTypeId": "eventType2",
    "eventTypeName": "Fun",
    "eventTypeDescription": "A fun event where you can relax and meet others."
}
```

> Status: 201

### GET mewm/types/

Result:
```
{
   "eventTypes":[
      {
         "eventTypeDescription":"A fun event where you can relax and meet others.",
         "eventTypeId":"eventType2",
         "eventTypeName":"Fun"
      },
      {
         "eventTypeId":"eventType1",
         "eventTypeName":"Workshop",
         "eventTypeDescription":"A technical talk"
      }
   ]
}
```

> Status: 200

### GET mewm/types/eventType1

Result:
```
{
   "eventTypeId":"eventType1",
   "eventTypeName":"Workshop",
   "eventTypeDescription":"A technical talk"
}
```

> Status: 200


### PATCH mewm/types/eventType1
```
{
	"eventTypeDescription": "A technical talk"
}
```
> Status: 200

### DELETE mewm/types/eventType2

> Status: 200

2021-03-18 04:23 UTC, andrewdimmer requested changes
Looks really good, but I think we're missing the `permissions` object from the data type, create, and update functions. Can you take a look at that for me?

2021-03-18 04:23 UTC, andrewdimmer commented on @types/modules/mewm/types.d.ts
> +  eventTypeDescription?: string;
Can we add the `permissions` object here?
```suggestion
  eventTypeDescription?: string;
  permissions?: UASPermissionSwitchConfig<boolean>;
```

2021-03-18 04:23 UTC, andrewdimmer commented on @types/modules/mewm/types.d.ts
> +  eventTypeDescription: string;
Can we add the `permissions` object here?
```suggestion
  eventTypeDescription: string;
  permissions: UASPermissionSwitchConfig<boolean>;
```

2021-03-18 04:23 UTC, andrewdimmer commented on functions/src/modules/mewm/types/createType.ts
> +      eventTypeDescription: { rules: ["string", "emptystring"] },
Can we add the permission object here?

2021-03-18 04:23 UTC, andrewdimmer commented on functions/src/modules/mewm/types/createType.ts
> +
Can we autofill the description to an empty string and the permissions to an empty object if none is provided?

2021-03-18 04:23 UTC, andrewdimmer commented on functions/src/modules/mewm/types/listTypes.ts
> +
Minor nitpick, but can we remove this extra line as long as we're making other changes?
```suggestion
```

2021-03-18 04:23 UTC, andrewdimmer commented on functions/src/modules/mewm/types/updateType.ts
> +      eventTypeDescription: { rules: ["string", "emptystring"] },
Can we add the permissions object here?

2021-03-22 02:06 UTC, andrewdimmer approved these changes
Looks good to me!

2021-03-22 02:11 UTC, merged