Prize category prize modules, #35
GrizzHacks/hackathon-portal pull request #93
Opened 2021-03-14 20:55 UTC by ejub-has

In this pull request I have created both delete and get for prizes under a specific category. This resolves part of issue #35

2021-03-17 23:01 UTC, nicksinishtaj commented
Can you do the following for 93-95, each PR accordingly.

Copy paste this comment I have right below here, and then update with your endpoints and the data you're using to verify in the API explorer. Just makes it easier when referencing back to these what test data to run.

### Tests via API Explorer (ORGANIZER user):
**POST mewm/events/**

```JSON
{
    "eventId": "event1",
    "eventName": "Ejub's Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": true
}
```

> Status: 201

**GET mewm/events/event1**

mewm/events/event1

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's Excel Contest"}

**PATCH mewm/events/event1**

```JSON
{
	"eventName": "ejub excel"
}
```

> Status: 200

**GET mewm/events/event1**

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}

**POST mewm/events/**

```JSON
{
    "eventId": "event2",
    "eventName": "Ejub's LIVE Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": false
}
```

> Status: 201

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"},{"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}]}



**DELETE mewm/events/event1**

> Status: 200

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"}]}

2021-04-01 04:33 UTC, trode21 commented
Tests via API Explorer (ORGANIZER user):
POST pm/categories/1/prizes

{
"prizeId": "1",
"prizeDisplayName": "the best",
"prizePrice": "1,000",
"prizeListingName": "toy",
"prizeURL" : "www.toy.com",
"prizeasin" : "dscfdsdbnksdnsal"
}
Status: 201

GET pm/categories/1/prizes/1

pm/categories/1/prizes/1

Status: 200
Body:{"prizeURL":"www.toy.com","prizeDisplayName":"thebest","prizeId":"1","prizePrice":"1,000","prizeasin":"dscfdsdbnksdnsal","prizeListingName":"toy"}

PATCH pm/categories/1/prizes/1

{
"prizePrice":"5,000"
}
Status: 200

GET pm/categories/1/prizes/1

Status: 200
Body:{"prizeURL":"www.toy.com","prizeDisplayName":"thebest","prizeId":"1","prizeasin":"dscfdsdbnksdnsal","prizeListingName":"toy","prizePrice":"5,000"}

POST pm/categories/1/prizes/


{
"prizeId": "2",
"prizeDisplayName": "the best",
"prizePrice": "1,000",
"prizeListingName": "toy",
"prizeURL" : "www.toy.com",
"prizeasin" : "dscfdsdbnksdnsal"
}
Status: 201

GET pm/categories/1/prizes/

Status: 200
Body: {"Prize":[{"prizeURL":"www.toy.com","prizeDisplayName":"the best","prizeId":"1","prizePrice":"1,000","prizeasin":"dscfdsdbnksdnsal","prizeListingName":"toy"},{"prizeURL":"www.toy.com","prizeDisplayName":"the best","prizeId":"2","prizePrice":"1,000","prizeasin":"dscfdsdbnksdnsal","prizeListingName":"toy"}]}

DELETE pm/categories/1/prizes/1

Status: 200

GET mewm/events/

Status: 200
Body: {"Prize":[{"prizeURL":"www.toy.com","prizeDisplayName":"the best","prizeId":"2","prizePrice":"1,000","prizeasin":"dscfdsdbnksdnsal","prizeListingName":"toy"}]}

2021-04-01 05:29 UTC, andrewdimmer requested changes
Few minor changes basically just for naming convention, then we should be good to go!

2021-04-01 05:29 UTC, andrewdimmer commented on @types/modules/pm/prize.d.ts
> +    prizeasin?: string;
Can we do ASIN as all caps?
```suggestion
    prizeASIN?: string;
```

2021-04-01 05:29 UTC, andrewdimmer commented on @types/modules/pm/prize.d.ts
> +
Can we do ASIN as all caps?
```suggestion
    prizeASIN: string;
```

2021-04-01 05:29 UTC, andrewdimmer commented on @types/modules/stpm/prizeCatagories.d.ts
> +type Prize = {
This shouldn't be required.

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/createPrize.ts
> +        prizeasin: { rules: ["string"], required: true  },
Can we do ASIN as all caps?
```suggestion
        prizeASIN: { rules: ["string"], required: true  },
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/createPrize.ts
> +        prizeURL: { rules: ["string"], required: true  },
This should be camelCase as defined in the data type.

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/createPrize.ts
> +    .collection("Prize")
This needs to be nested, so I think that it will end up as follows:
```suggestion
    .collection("prizeCategories)
    .doc(req.params.categoryId)
    .collection("prizes")
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/deletePrize.ts
> +    .collection("Prize")
This needs to be nested, so I think that it will end up as follows:
```suggestion
    .collection("prizeCategories)
    .doc(req.params.categoryId)
    .collection("prizes")
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/getPrize.ts
> +      .collection("Prize")
This needs to be nested, so I think that it will end up as follows:
```suggestion
    .collection("prizeCategories)
    .doc(req.params.categoryId)
    .collection("prizes")
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/getPrize.ts
> +          errorHandler('Prizes ${req.params.Prizeid} has no data');
I think this should be `prizeId` and not `Prizeid`.
```suggestion
          errorHandler('Prizes ${req.params.prizeId} has no data');
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +    .collection("Prize")
This needs to be nested, so I think that it will end up as follows:
```suggestion
    .collection("prizeCategories)
    .doc(req.params.categoryId)
    .collection("prizes")
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/index.ts
> +import listPrizes from "./listPrize";
This endpoint should be `listPrizes`...
```suggestion
import listPrizes from "./listPrizes";
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +import type { ExpressFunction } from "../../../../@types";
This file should be `listPrizes.tsx`

2021-04-01 05:29 UTC, andrewdimmer commented on @types/modules/pm/prize.d.ts
> +    Prize: PMPrize[];
This should be lower case and plural.
```suggestion
    prizes: PMPrize[];
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +  const Prize: PMPrize[] = [];
This should be lower case and plural.
```suggestion
  const prizes: PMPrize[] = [];
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +    Prize.push(doc.data() as PMPrize );
This should be lower case and plural.
```suggestion
    prizes.push(doc.data() as PMPrize );
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +  res.status(200).send(JSON.stringify({ Prize } as PMPrizeList));
This should be lower case and plural.
```suggestion
  res.status(200).send(JSON.stringify({ prizes } as PMPrizeList));
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +export default listPrize;
This should be plural.
```suggestion
export default listPrizes;
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/listPrize.ts
> +const listPrize: ExpressFunction = (req, res, next) => {
This should be plural.
```suggestion
const listPrizes: ExpressFunction = (req, res, next) => {
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/updatePrize.ts
> +    organizer: { accepted: ValidateOrganizer },
This should be camelCase.
```suggestion
    organizer: { accepted: validateOrganizer },
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/updatePrize.ts
> +const ValidateOrganizer: ExpressFunction = (req, res, next) => {
This should be camelCase.
```suggestion
const validateOrganizer: ExpressFunction = (req, res, next) => {
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/updatePrize.ts
> +      prizeurl: { rules: ["string"], },
You've got URL twice...
```suggestion
     },
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/updatePrize.ts
> +      prizeasin: { rules: ["string"]},
This should be all caps.
```suggestion
      prizeASIN: { rules: ["string"]},
```

2021-04-01 05:29 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/updatePrize.ts
> +    .collection("Prize")
This needs to be nested, so I think that it will end up as follows:
```suggestion
    .collection("prizeCategories)
    .doc(req.params.categoryId)
    .collection("prizes")
```

2021-04-01 06:02 UTC, andrewdimmer approved these changes
Looks good to me, you are all set to merge!

2021-04-01 06:06 UTC, merged