PM Prize Category Group API
GrizzHacks/hackathon-portal pull request #94
Opened 2021-03-14 21:16 UTC by ejub-has

Adding listGroups, and createGroups to help resolve issue #37

2021-03-17 23:01 UTC, nicksinishtaj commented
Can you do the following for 93-95, each PR accordingly.

Copy paste this comment I have right below here, and then update with your endpoints and the data you're using to verify in the API explorer. Just makes it easier when referencing back to these what test data to run.

### Tests via API Explorer (ORGANIZER user):
**POST mewm/events/**

```JSON
{
    "eventId": "event1",
    "eventName": "Ejub's Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": true
}
```

> Status: 201

**GET mewm/events/event1**

mewm/events/event1

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's Excel Contest"}

**PATCH mewm/events/event1**

```JSON
{
	"eventName": "ejub excel"
}
```

> Status: 200

**GET mewm/events/event1**

> Status: 200
> Body: {"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}

**POST mewm/events/**

```JSON
{
    "eventId": "event2",
    "eventName": "Ejub's LIVE Excel Contest",
    "eventDescription": "Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ",
    "virtual": false
}
```

> Status: 201

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"},{"eventId":"event1","virtual":true,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"ejub excel"}]}



**DELETE mewm/events/event1**

> Status: 200

**GET mewm/events/**

> Status: 200
> Body: {"miniEvents":[{"eventId":"event2","virtual":false,"eventDescription":"Ejub displays his magnificent skill of beautiful art in Microsoft Excel, but in real-time on a white board. They refer to Ejub as the Picasso of Spreadsheets ","eventName":"Ejub's LIVE Excel Contest"}]}

2021-04-01 01:31 UTC, andrewdimmer requested changes
Awesome start! Few minor changes, then you should be good to go!

2021-04-01 01:31 UTC, andrewdimmer commented on @types/modules/pm/groups.d.ts
> +    prizeGroupOrder?: Array<string>;
Minor nitpick, but generally unless there is a really complicated type, it is generally easier to use `[]` to denote an array.
```suggestion
    prizeGroupOrder?: string[];
```

2021-04-01 01:31 UTC, andrewdimmer commented on @types/modules/pm/groups.d.ts
> +    prizeGroupOrder: Array<string>;
Minor nitpick, but generally unless there is a really complicated type, it is generally easier to use `[]` to denote an array. Also, might want to have this optional and autofill it upon creation, as there won't be any prizes when it gets created.
```suggestion
    prizeGroupOrder?: string[];
```

2021-04-01 01:31 UTC, andrewdimmer commented on @types/modules/pm/groups.d.ts
> +    prizeGroupOrder: Array<string>;
Minor nitpick, but generally unless there is a really complicated type, it is generally easier to use `[]` to denote an array.
```suggestion
    prizeGroupOrder: string[];
```

2021-04-01 01:31 UTC, andrewdimmer commented on @types/modules/mewm/companies.d.ts
> +declare interface STPMCompanyUpdateRequest {
Is this document required? I think this is a stray artifact and can be deleted.

2021-04-01 01:31 UTC, andrewdimmer commented on @types/modules/stpm/prizeCatagories.d.ts
> +type Prize = {
Is this document required for this PR? I think this is a stray artifact and can be deleted.

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/deletePrize.ts
> +import type { ExpressFunction } from "../../../../@types";
Is this document required in this PR? I think this is a stray artifact and can be deleted.

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/categories/prizes/getPrize.ts
> +import type { ExpressFunction } from "../../../../@types";
Is this document required in this PR? I think this is a stray artifact and can be deleted.

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/createGroup.ts
> +      required: true},
I think we should be able to get away with having this be optional, and then just autofill to an empty array if it is not given.

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/createGroup.ts
> +      .collection("PrizeCategoryGroup")
Can we call this `prizeGroups` to stick with the naming convention from other modules?
```suggestion
      .collection("prizeGroups")
```

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/deleteGroup.ts
> +    .collection("PrizeCategoryGroup")
Can we call this `prizeGroups` to stick with the naming convention from other modules?
```suggestion
    .collection("prizeGroups")
```

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/getGroup.ts
> +    .collection("PrizeCategoryGroup")
Can we call this `prizeGroups` to stick with the naming convention from other modules?
```suggestion
    .collection("prizeGroups")
```

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/listGroups.ts
> +    .collection("PrizeCategoryGroup")
Can we call this `prizeGroups` to stick with the naming convention from other modules?
```suggestion
    .collection("prizeGroups")
```

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/updateGroup.ts
> +    .collection("PrizeCategoryGroup")
Can we call this `prizeGroups` to stick with the naming convention from other modules?
```suggestion
    .collection("prizeGroups")
```

2021-04-01 01:31 UTC, andrewdimmer commented on functions/src/modules/pm/groups/createGroup.ts
> +
Can we add a check to basically say if `prizeGroupOrder` is `undefined`, set this equal to an empty array?

2021-04-01 01:50 UTC, andrewdimmer requested changes
Just a few more changes...

2021-04-01 01:50 UTC, andrewdimmer commented on @types/modules/pm/groups.d.ts
> +    prizeGroupOrder?: string[];
Actually, this is redundant now due to inheritance...
```suggestion
```

2021-04-01 01:50 UTC, andrewdimmer commented on functions/src/modules/pm/groups/createGroup.ts
> +      required: true},
I think we should be able to get rid this.
```suggestion
      },
```

2021-04-01 02:04 UTC, andrewdimmer commented on @types/modules/mewm/companies.d.ts
> +  overriddenBenefits?: { [key: string]: string };
```suggestion
  overriddenBenefits?: STPMTierUpdateRequest;
```

2021-04-01 02:04 UTC, andrewdimmer commented on @types/modules/mewm/companies.d.ts
> + overriddenBenefits: { [key: string]: string };
```suggestion
  overriddenBenefits: STPMTierUpdateRequest;
```

2021-04-01 02:06 UTC, andrewdimmer approved these changes
Provided the build tests pass, you should be all set to merge!

2021-04-01 02:10 UTC, merged